name: Update README

on:
  create:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update README
        run: |
          sed -i "s/\[Datum\]\-\[Thema\]/$(basename `git rev-parse --show-toplevel`)/g" README.md
          sed -i "s/\[repo\-name\]/$(basename `git rev-parse --show-toplevel`)/g" README.md
          git add README.md
          git commit -m "Update README"
          git push origin main
