name: Update README

on:
  create:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace placeholders in README
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '[Datum]-[Thema]'
          replace: ${{ github.repository }}
          include: 'README.md'
